package se.sjv.test
 
import com.sample.models.Message;
 
rule "Hello World"
ruleflow-group "group1"
//auto-focus true
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Mine: Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
ruleflow-group "group1"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
