//created on: Jan 8, 2013
//Adding a comment to my rule
package org.acme.insurance

rule "Should not be driving"
dialect "mvel"

    when
        driver : Driver(age >= 97)
	policy : Policy(price == 0, policyType == "AUTO")
    then
        modify(policy) {price = 1000}
        System.out.println("fired rule " + kcontext.getRule().getName());
        

end



rule "Can't reach the pedal"
dialect "mvel"

    when
        driver : Driver(age <= 0)
	policy : Policy(price == 0, policyType == "AUTO")
    then
        System.out.println("fired rule " + kcontext.getRule().getName());
        

end
